name: Sync to Public Repo

on:
  push:
    branches:
      - astrogency-free

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      BRANCH_NAME: "sync-${{ github.run_id }}"

    steps:
      - name: Checkout the Private Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: astrogency-free
          fetch-depth: 0
          lfs: true

      - name: Set up Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup and Push to Public Repo
        run: |
          # Add public remote
          git remote add public git@github.com:unfolding-io/Astrogency.git
          git fetch public --prune

          # Create and push branch
          git checkout -b "$BRANCH_NAME"
          git push public "$BRANCH_NAME" --force

      - name: Checkout Public Repo for PR Creation
        uses: actions/checkout@v4
        with:
          repository: unfolding-io/Astrogency
          ref: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: unfolding-io/Astrogency
          branch: ${{ env.BRANCH_NAME }}
          base: astrogency-free
          title: "Sync astrogency-free branch from private repo"
          body: "This PR syncs the latest changes from the astrogency-free branch in the private repo."